micronaut:
    application:
        name: inventory-service
    server:
        port: 8082
    config-client:
        enabled: true
    caches:
        discovery-client:
            enabled: false
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
    health:
        enabled: true
        sensitive: false
tracing:
    jaeger:
        enabled: true
        sampler:
            probability: 1